[build]
  base = "lengua-esp-viva"
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

# Redirecionamento de todas as rotas da API para as Serverless Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200